apiVersion: v1
kind: Service
metadata:
  # We named it redis because that is how the voting app connects to it, we cannot name  redis-service
  name: redis
  label: 
    name: redis-service
    app: demo-voting-app
spec:
  type: ClusterIP
  selector:
    name: redis-pod
    app: demo-voting-app
  ports:
  - port: 6379
    targetPort: 6379
