apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    app: demo-voting-app
    name: voting-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: voting-app-pod
      app: demo-voting-app
    spec:
      containers:
        - name: voting-app-container
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      name: voting-app-pod
      app: demo-voting-app
